apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-bar-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-bar-app
  template:
    metadata:
      labels:
        app: kube-bar-app
    spec:
      containers:
        - name: kube-bar-app
          image: vlukyane/minikube_try:bar
          ports:
            - containerPort: 3002
              protocol: TCP
