kind: Service
apiVersion: v1
metadata:
  name: react-nginx-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32009
  selector:
    app: react-nginx
